### ISSUE TITLE
Incorrect port in docker-compose

### ISSUE THREAD

**Issue by omid-jf** [CEDARS-NLP/CEDARS#34]
**Problem:**
`cedars/gunicorn.conf.py` is specifying 5001 as the binding port; hence, the Flask app will run on port 5001. 
However, `docker-compose.yml` is mapping port 5001 of host to port 5000 of container.

Tested in macOS Sonoma.

**Solution 1:**
Changing binding port in `cedars/gunicorn.conf.py` to 5000.

**Solution 2:**
Changing port mapping for the `web` service in `docker-compose.yml` to 5001:5001

**Comment by ygivenx** [comment]
Hi Omid, thanks for opening the issue -  because of the nginx proxy, this docker compose port mapping is not required. However, it would not run if nginx was not used. I'll remove this line. Did you face any issues running the docker compose?
