### ISSUE TITLE
problems with event date

### ISSUE THREAD

**Issue by simon-hans** [CEDARS-NLP/CEDARS#40]
Once an event date has been recorded, it does not display. If we navigate to a different patient and come back, the default note date appears in the entry field, with no trace of the previous, saved entry.

Also, trying to just enter the default event date (i.e. the current note date), there is no response from the interface, not sure what is going on, does not seem to register?

**Comment by ygivenx** [comment]
It does work as expected (shared screenshots to show this) - users can potentially multiple event dates in case they do not skip after event.
