### ISSUE TITLE
Create mongo index post data insertion to optimize speed

### ISSUE THREAD

**Issue by ygivenx** [CEDARS-NLP/CEDARS#44]

**Comment by ygivenx** [comment]
When ever someone starts adjudicating - check if the queue is empty and if it is, and there are no indices on annotations collection create it.

**Comment by ygivenx** [comment]
in the project detail page - if an index does not exist for annotations - let the admin create the index manually.

**Comment by Kayan1920** [comment]
Indices for DB are now created for all collections when the project is initialised. Creating indices post-data insertion has been found to be much slower.
